# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make it fail
        run: |
          echo I make it fail
          exit 1

  after_fail:
    runs-on: ubuntu-latest
    needs: ['build']
    if: always()
    steps:
      - name: Run after the fail
        run: |
          echo I run after the fail

  after_fail_with_failure:
    runs-on: ubuntu-latest
    needs: ['build']
    if: always() && failure()
    steps:
      - name: Run after the fail
        run: |
          echo I run after the fail

  after_fail_with_success:
    runs-on: ubuntu-latest
    needs: ['build']
    if: always() && success()
    steps:
      - name: Run after the success
        run: |
          echo I run after the success